services:
  - type: web
    name: mockpro-app
    env: node
    plan: free
    repo: https://github.com/Thamizh-01/Mock_interview.git
    branch: main
    buildCommand: npm run build-client && cd server && npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GOOGLE_CLIENT_ID
        value: 961158324129-blao26on15r1hpmbe4nfthha6bod7vh9.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_ID
        value: 961158324129-blao26on15r1hpmbe4nfthha6bod7vh9.apps.googleusercontent.com
    autoDeploy: true
